In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

Pandas: 3.0.0
NumPy: 2.4.2

In [6]:
df = pd.read_csv("../data/processed/subway_trains_delayed_cleaned.csv")

df.head()

,Day Type Name,division,delays,day_type,line,Month Name,reporting_category,Year,Quarter
0,Weekday,A DIVISION,1,1,GS,April,Crew Availability,2023,Qtr 2
1,Weekday,A DIVISION,1,1,GS,August,Crew Availability,2020,Qtr 3
2,Weekday,A DIVISION,1,1,GS,December,Crew Availability,2022,Qtr 4
3,Weekday,A DIVISION,1,1,GS,February,Crew Availability,2023,Qtr 1
4,Weekday,A DIVISION,1,1,GS,March,Crew Availability,2024,Qtr 1

In [7]:
# Create a proper datetime column for time-series analysis
df['month_date'] = pd.to_datetime(
    df['Month Name'] + ' ' + df['Year'].astype(str),
    format='%B %Y'
)

df[['Month Name', 'Year', 'month_date']].head()

  Month Name  Year month_date
0      April  2023 2023-04-01
1     August  2020 2020-08-01
2   December  2022 2022-12-01
3   February  2023 2023-02-01
4      March  2024 2024-03-01

In [8]:
df.drop(columns=['day_type'], inplace=True)

In [9]:
df.columns

Index(['Day Type Name', 'division', 'delays', 'line', 'Month Name',
       'reporting_category', 'Year', 'Quarter', 'month_date'],
      dtype='str')

In [10]:
# Save final processed dataset for analysis
df.to_csv("../data/processed/subway_trains_delayed_cleaned.csv", index=False)